name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (you can change the version if necessary)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-build-

      # Step 4: Set execute permissions for Gradlew
      - name: Grant execute permission for gradlew
        run: sudo chmod +x ./gradlew

      # Step 5: Download dependencies
      - name: Download Dependencies
        run: ./gradlew androidDependencies

      # Step 6: Run the build
      - name: Build with Gradle
        run: ./gradlew build

      # Step 7: Run tests
      - name: Run tests
        run: ./gradlew lint test

      # Step 8: Store build artifacts (APK)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/

      # Step 9: Store test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/test-results

      # Step 10: Upload reports
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: app/build/reports
