name: Android CI
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build: 
    runs-on: windows - latest
    steps:
      - name: Checkout
        uses: actions/checkout@2.3.2
      - name: Setup JDK
        uses: actions/setup-java@4.3.0
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v3.2.1-node20
        with: 
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
